### PR TITLE
Feature/frontend/viewcomponent

### PR DESCRIPTION
**Pull request by Wh1teh**
chonker

### CODE REVIEW

**Comment by Wh1teh** [comment]
varmaan node version takia failaa preact signaaleissa

**Comment by Wh1teh** [comment]
some tests fail presumably because of async behavior, trying to fix

**Comment by Wh1teh** [comment]
tests should now pass in GHA

**Review by mikakorkiakoski — APPROVED** [review]
Tested, did not break anything

**Pull request merged**
